name: Second python
# se ejecuta cuando se mergea
on:
  push
jobs:
  first-job:
    name: GithubAction python2 test
    runs-on: ubuntu-latest
    steps:    
      - name: Check directory
        run: |
          git clone https://jimenazo97:5d780102ea936e90b0301bdcd42f40700082f60e@github.com/jimenazo97/validaciones.git
          echo $GITHUB_WORKSPACE
          ls -l $GITHUB_WORKSPACE/test_validations
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pyyaml
          python -m pip install mysql-connector
          python -m pip install GitPython
      - name: Run script
        run: python $GITHUB_WORKSPACE/validaciones/.github/workflows/prueba.py $GITHUB_WORKSPACE/validaciones
